### ISSUE TITLE
Do a first release

### ISSUE THREAD

**Issue by GitMensch** [DmLam/GrammarEdit#1]
Thank you for releasing the source under GPL!

Do you think you can provide a release (by tagging a version you see to be stable, and ideally editing the GitHub release entry to add binaries)?

**Comment by DmLam** [comment]
Re: [DmLam/GrammarEdit] Do a first release (#1)


Hello, Simon.

You wrote 30 июня 2018 г., 21:37:52:

I don't see any sense realising a version, because the source are the same as released on GoldParser.org,
only updated to be built with new libraries version





Thank you for releasing the source under GPL!
Do you think you can provide a release (by tagging a version you see to be stable, and ideally editing the GitHub release entry to add binaries)?
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.





--
Regards,,
 Dmitry                          mailto:lamdan@mail.ru

**Comment by GitMensch** [comment]
> I don't see any sense realising a version, because the source are the same as released on GoldParser.org, only updated to be built with new libraries version

In this case creating a tag (for 1.2 version) would still make sense as it provides a "base version" in source control, too.
Obvious this is no completely new version but a binary that matches the current source code and uses current libraries to download from GitHub would provide a reason for a 1.2.1 binary.

What do you think?

**Comment by DmLam** [comment]
Re: [DmLam/GrammarEdit] Do a first release (#1)


Hello, Simon.

You wrote 1 июля 2018 г., 20:14:48:

Ahh... Of course, you right, I created the tag :)









I don't see any sense realising a version, because the source are the same as released on GoldParser.org, only updated to be built with new libraries version


In this case creating a tag (for 1.2 version) would still make sense as it provides a "base version" in source control, too.
Obvious this is no completely new version but a binary that matches the current source code and uses current libraries to download from GitHub would provide a reason for a 1.2.1 binary.
What do you think?
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.





--
Regards,,
 Dmitry                          mailto:lamdan@mail.ru

**Comment by GitMensch** [comment]
> I created the tag :)

Wonderful.

Can you please edit https://github.com/DmLam/GrammarEdit/releases/tag/Version_1.2 and include http://goldparser.org/builder/files/GrammarEdit.zip there (this would *at least* provide a https download option and a fallback if/when goldparser.org vanishes)?

And as there are already [some changes since the old version](https://github.com/DmLam/GrammarEdit/compare/Version_1.2...master) (which was built with old tools / external libraries):
Can I also request a 1.2.1/1.3 release with current master using current libraries (I promise to accept a "not yet, there will be a when we have more things done for 1.3 later")?

**Comment by DmLam** [comment]
> Can you please edit https://github.com/DmLam/GrammarEdit/releases/tag/Version_1.2 and include http://goldparser.org/builder/files/GrammarEdit.zip there

Do you want me to include binaries into the commit tagged Version1.2? Sorry, I'm not an advanced github user, and not sure I understand.

> Can I also request a 1.2.1/1.3 release with current master using current libraries

"Not yet", I think. I don't intend to develop the project (for now at least), so this repository is for all the people who asked me for the source code last years.

**Comment by GitMensch** [comment]
> Do you want me to include binaries into the commit tagged Version1.2?

Not in the commit, but when you go to https://github.com/DmLam/GrammarEdit/releases/tag/Version_1.2 you can click on "edit release" and add release notes and the binaries.

As it is the old version it would be good to upload the old binaries there.

**Comment by DmLam** [comment]
Ok, I added GrammarEdit.exe to release, not the old executable, but the one I built from the updated sources.

**Comment by GitMensch** [comment]
Is there something missing? I've downloaded the binary and used Menu Options>anything, result:

~~~
---------------------------
Grammaredit
---------------------------
Error reading sePreview.Lines.Strings: Property Strings does not exist.
---------------------------
OK   
---------------------------
~~~

**Comment by GitMensch** [comment]
There may be an issue with the updated library: Search shows:

~~~
---------------------------
Grammaredit
---------------------------
No search engine has been assigned.
---------------------------
OK   
---------------------------
~~~

**Comment by DmLam** [comment]
Fixed

**Comment by GitMensch** [comment]
That was quick, thank you, works!
